name: MILDTG Unit Tests
on:
  push:
    branches_ignore:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.16', '1.17', '1.18', '1.19', '1.20', '1.21', '1.22', '1.23']
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Go
      - name: setup
        uses: actions/setup-go@v5.0.0
        with:
          go-version: ${{ matrix.go-version }}

      # Set up the environment
      - name: unit-tests
        run: make test
        depends-on: [ setup ]

      # Run benchmarks
      - name: Run benchmarks
        run: make bench
        depends-on: [ setup ]

