name: MILDTG Unit Tests
on:
  push:
    branches:
      - !main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Go
      - name: setup
        uses: actions/setup-go@v5.0.0
        with:
          go-version-file: './go.mod'

      # Set up the environment
      - name: unit-tests
        run: make test
        depends-on: [ setup ]

      # Run benchmarks
      - name: Run benchmarks
        run: make bench
        depends-on: [ setup ]

