name: MILDTG Unit Tests
on:
  push:
    branches:
      - '!main'
      - '**'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.17', '1.18', '1.19', '1.20', '1.21', '1.22', '1.23' ]
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Go
      - name: setup
        uses: actions/setup-go@v5.0.0
        with:
          go-version: ${{ matrix.go-version }}

      - name: test shuffle
        run: make test

  bench:
    runs-on: ubuntu-latest
    needs: test
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Go
      - name: setup
        uses: actions/setup-go@v5.0.0
        with:
          go-version: '1.23'

      # Set up the environment
      - name: bench-tests
        run: make bench

